### ISSUE TITLE
Simple example panics

### ISSUE THREAD

**Issue by dignifiedquire** [jfbilodeau/yew_form#3]
Getting this panic on the current master code, my code is the same as in the examples folder, this happens as soon as `oninput` gets triggered for me.

```
webpack:///./frontend/pkg/index_bg.js?:392 panicked at 'called `Option::unwrap()` on a `None` value', /Users/dignifiedquire/.cargo/git/checkouts/yew_form-0d273cf04f678139/f7c824c/yew_form/src/form.rs:24:9
```

**Comment by jfbilodeau** [comment]
Thanks for reporting @dignifiedquire. I'll look into that.

**Comment by dignifiedquire** [comment]
I have a working version here: https://github.com/dignifiedquire/yew_form/tree/fix-refs

**Comment by jfbilodeau** [comment]
Thanks @dignifiedquire. Any chance you could send a PR my way?

**Comment by dignifiedquire** [comment]
Done in #4
